root: '/media/notalinux/_dev_sdb3/Website/reduxelite'
#root: '/media/notalinux/_dev_sdb3/Website/elitereduxv152'
# pokedex.py
species: '/include/constants/species.h'
entries: '/src/data/pokemon/pokedex_entries.h'
formes: '/src/data/pokemon/form_species_tables.h'
base_stats: '/src/data/pokemon/base_stats.h'
evo: '/src/data/pokemon/evolution.h'
pokedex_output: './output/pokedex.json'
# trainer_parties.py
trainers: '/src/data/trainers.h'
parties: '/src/data/trainer_parties.h'
order: './trainer_order'
trainers_output: './output/trainersets.js'
trainers_map_output: './output/maps.json'
trainers_idmap : './output/trainersidmaps.js'
# sprite.py
sprites: '/graphics/pokemon/'
sprites_output: './output/sprites/'
# abilities.py
# abilities: '/include/constants/abilities.h'
abilities: '/src/data/text/abilities.h'
abilities_output: './output/abilities.json'
abilities_description_output: './output/ability_descriptions.js'
# moves.py
moves: '/src/data/battle_moves.h'
moves_output: './output/moves.json'
# items.py
items: ''
items_output: './output/items.json'
#saveloader.py
save_abis:  '/include/constants/abilities.h'
save_mons:  '/include/constants/species.h'
save_moves: '/include/constants/moves.h'
save_items: '/include/constants/items.h'
save_output: './output/loadsave.js'
